'use client'
import { useState } from 'react'
import { motion } from 'framer-motion'
import {
  Database, FileCode, FolderOpen, RefreshCw, CheckCircle,
  ChevronDown, ChevronRight, Zap, Play, Copy, Check, Table2,
} from 'lucide-react'
import { useMutation } from '@tanstack/react-query'
import { useDbtModels, useDbtRuns, useGenerateDbt } from '@/lib/queries'
import { optimizerApi, analystApi } from '@/lib/api'
import { DEMO_DBT_MODELS, DEMO_DBT_RUNS } from '@/lib/demo'
import { CodeBlock } from '@/components/ui/CodeBlock'
import { useToast } from '@/components/ui/Toaster'
import type { DbtModel, DbtRun, OptimizerResult, AntiPattern } from '@/lib/types'

const C = {
  bg: '#080F1C', card: '#0F2540', border: '#1A3A5C',
  accent: '#0EA5E9', emerald: '#10B981', amber: '#F59E0B', red: '#EF4444', violet: '#7C3AED',
  textPrimary: '#F1F5F9', textMuted: '#64748B', textLabel: '#4B6B8E',
}

interface RunResult {
  row_count?: number
  execution_time_ms?: number
  savings_percent?: number
  columns?: string[]
  rows?: (string | number | null)[][]
}

interface DbtRunExtended extends DbtRun {
  models_succeeded?: number
  models_failed?: number
  tests_passed?: number
  run_output?: string
  duration_ms?: number
  created_at?: string
}

const STEP_LABELS = ['Introspecting schema…', 'Proposing star schema…', 'Writing SQL models…', 'Running dbt…']

const PLACEHOLDER_SQL = `-- fct_revenue_by_category: Monthly revenue breakdown by product category
-- Generated by OrchestrAI DbtModelingAgent  |  Run or Optimize below

WITH order_items_enriched AS (
    SELECT
        oi.order_id,
        p.category,
        oi.quantity * oi.unit_price          AS line_revenue,
        DATE_TRUNC('month', o.created_at)    AS revenue_month
    FROM order_items oi
    JOIN products p ON oi.product_id = p.id
    JOIN orders   o ON oi.order_id   = o.id
    WHERE o.status IN ('completed', 'shipped')
),
monthly_agg AS (
    SELECT
        revenue_month,
        category,
        COUNT(DISTINCT order_id)             AS order_count,
        ROUND(SUM(line_revenue)::NUMERIC, 2) AS total_revenue
    FROM order_items_enriched
    GROUP BY revenue_month, category
)
SELECT
    revenue_month,
    category,
    order_count,
    total_revenue,
    ROUND(100.0 * total_revenue / SUM(total_revenue) OVER (PARTITION BY revenue_month), 1) AS revenue_share_pct
FROM monthly_agg
ORDER BY revenue_month DESC, total_revenue DESC
LIMIT 50;`

function StatusPill({ status }: { status: string }) {
  const map: Record<string, { color: string; bg: string }> = {
    success: { color: C.emerald, bg: 'rgba(16,185,129,0.12)' },
    error:   { color: C.red,    bg: 'rgba(239,68,68,0.12)' },
    running: { color: C.accent, bg: 'rgba(14,165,233,0.12)' },
    pending: { color: C.amber,  bg: 'rgba(245,158,11,0.12)' },
  }
  const s = map[status] || { color: C.textMuted, bg: 'rgba(100,116,139,0.12)' }
  return (
    <span style={{ fontSize: 10, fontWeight: 700, padding: '2px 7px', borderRadius: 5, background: s.bg, color: s.color, letterSpacing: '0.05em', textTransform: 'uppercase' as const }}>
      {status}
    </span>
  )
}

export default function DbtPage() {
  const toast = useToast()
  const { data: models, isLoading: modelsLoading, refetch: refetchModels } = useDbtModels()
  const { data: runs, isLoading: runsLoading, refetch: refetchRuns } = useDbtRuns()
  const generateDbt = useGenerateDbt()

  const [stagingOpen, setStagingOpen] = useState(true)
  const [martsOpen, setMartsOpen] = useState(true)
  const [generateStep, setGenerateStep] = useState(-1)
  const [selectedModel, setSelectedModel] = useState<DbtModel | null>(null)

  const [sql, setSql] = useState('')
  const [loadedModel, setLoadedModel] = useState<string | null>(null)
  const [optResult, setOptResult] = useState<OptimizerResult | null>(null)
  const [runResult, setRunResult] = useState<RunResult | null>(null)
  const [copied, setCopied] = useState(false)

  const _dbtDown = !modelsLoading && !runsLoading && !models && !runs
  const modelList: DbtModel[] = Array.isArray(models) && models.length > 0 ? models : (_dbtDown ? (DEMO_DBT_MODELS as unknown as DbtModel[]) : [])
  const staging = modelList.filter((m: DbtModel) => m.schema_layer === 'staging')
  const marts = modelList.filter((m: DbtModel) => m.schema_layer === 'marts')
  const runList = Array.isArray(runs) && runs.length > 0 ? runs : (_dbtDown ? DEMO_DBT_RUNS : [])
  const lastRun: DbtRunExtended | null = runList.length > 0 ? (runList[0] as unknown as DbtRunExtended) : null

  const optimize = useMutation({
    mutationFn: () => optimizerApi.optimize(sql).then(r => r.data),
    onSuccess: (data) => {
      setOptResult(data)
      toast(`Optimized — ${data.savings_percent?.toFixed(0) || 0}% faster, $${data.dollar_savings?.toFixed(4) || '0'} saved`, 'success')
    },
    onError: () => toast('Optimization failed — check the SQL syntax', 'error'),
  })

  const run = useMutation({
    mutationFn: () => analystApi.execute(sql).then(r => r.data),
    onSuccess: (data) => {
      setRunResult(data)
      toast(`Ran in ${data.execution_time_ms ?? 0}ms · ${data.row_count ?? 0} rows`, 'success')
    },
    onError: (e: unknown) => toast((e as { response?: { data?: { detail?: string } } })?.response?.data?.detail || 'Query failed — check the SQL', 'error'),
  })

  const insertTableRef = (m: DbtModel) => {
    const ref = `${m.schema_layer}.${m.name}`
    setSql(prev => (prev.trim() ? `${prev.replace(/\s+$/, '')} ${ref}` : ref))
    setLoadedModel(m.name)
    setSelectedModel(m)
  }

  const useOptimized = () => {
    if (optResult?.optimized_sql) {
      setSql(optResult.optimized_sql)
      toast('Optimized SQL loaded into the editor', 'info')
    }
  }

  const copyOptimized = () => {
    if (optResult?.optimized_sql) {
      navigator.clipboard.writeText(optResult.optimized_sql)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  const handleGenerate = async () => {
    setGenerateStep(0)
    toast('dbt generation queued — Groq LLM is writing models (30–60s)', 'info')
    const interval = setInterval(() => {
      setGenerateStep(s => {
        if (s >= 3) { clearInterval(interval); return 3 }
        return s + 1
      })
    }, 2500)
    try {
      await generateDbt.mutateAsync()
      setTimeout(() => { refetchModels(); refetchRuns() }, 5000)
      setTimeout(() => { refetchModels(); refetchRuns(); toast('dbt models ready — file tree updated', 'success') }, 15000)
    } catch {
      toast('dbt generation failed — check backend logs', 'error')
    } finally {
      clearInterval(interval)
      setGenerateStep(-1)
    }
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.3 }}
      style={{ display: 'flex', flexDirection: 'column', height: 'calc(100vh - 56px)', background: C.bg }}
    >
      {/* Page header */}
      <div style={{ padding: '20px 24px 16px', borderBottom: `1px solid ${C.border}`, background: C.card, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div>
          <h1 style={{ fontSize: 18, fontWeight: 700, color: C.textPrimary, margin: '0 0 4px' }}>dbt Assistant</h1>
          <p style={{ fontSize: 12, color: C.textMuted, margin: 0 }}>Auto-generate staging + mart models from raw destination tables using Groq LLM</p>
        </div>
        <button onClick={handleGenerate} disabled={generateDbt.isPending}
          style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '9px 18px', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer', background: C.emerald, color: 'white', border: 'none', opacity: generateDbt.isPending ? 0.6 : 1 }}>
          {generateDbt.isPending ? <RefreshCw size={14} style={{ animation: 'spin 1s linear infinite' }} /> : '✨'}
          Generate Models
        </button>
      </div>

      {/* Generation progress */}
      {generateStep >= 0 && (
        <div style={{ padding: '12px 24px', borderBottom: `1px solid ${C.border}`, background: '#09111E', display: 'flex', flexDirection: 'column', gap: 6 }}>
          {STEP_LABELS.map((label, i) => (
            <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '8px 12px', borderRadius: 8, background: C.card, opacity: i <= generateStep ? 1 : 0.3 }}>
              {i < generateStep ? <CheckCircle size={15} style={{ color: C.emerald }} />
                : i === generateStep ? <RefreshCw size={15} style={{ color: C.accent, animation: 'spin 1s linear infinite' }} />
                : <div style={{ width: 15, height: 15, borderRadius: '50%', border: `1px solid ${C.border}` }} />}
              <span style={{ fontSize: 13, color: C.textPrimary }}>{label}</span>
            </div>
          ))}
        </div>
      )}

      {/* Body */}
      <div style={{ display: 'flex', flex: 1, overflow: 'hidden' }}>
        {/* Left panel — model tree 38% */}
        <div style={{ width: '38%', borderRight: `1px solid ${C.border}`, display: 'flex', flexDirection: 'column', background: '#09111E', overflowY: 'auto' }}>
          <div style={{ padding: '14px 16px', borderBottom: `1px solid ${C.border}` }}>
            <p style={{ fontSize: 11, letterSpacing: '0.08em', textTransform: 'uppercase' as const, color: C.textLabel, fontWeight: 600, margin: '0 0 4px' }}>Models</p>
            <p style={{ fontSize: 11, color: C.textMuted, margin: 0 }}>Click a model to insert its table reference</p>
          </div>

          {modelsLoading ? (
            <div style={{ padding: 16, display: 'flex', flexDirection: 'column', gap: 8 }}>
              {[1,2,3,4].map(i => <div key={i} style={{ height: 36, borderRadius: 8, background: C.card, opacity: 0.6 }} />)}
            </div>
          ) : (
            <div style={{ padding: '8px 10px' }}>
              {/* Staging folder */}
              <button onClick={() => setStagingOpen(o => !o)}
                style={{ display: 'flex', alignItems: 'center', gap: 6, width: '100%', padding: '7px 8px', borderRadius: 7, background: 'none', border: 'none', cursor: 'pointer', color: C.textPrimary, fontSize: 13, fontWeight: 600 }}>
                {stagingOpen ? <ChevronDown size={13} /> : <ChevronRight size={13} />}
                <FolderOpen size={13} style={{ color: C.accent }} />
                <span>staging/</span>
                <span style={{ marginLeft: 'auto', fontSize: 10, color: C.textMuted }}>{staging.length}</span>
              </button>
              {stagingOpen && (
                <div style={{ marginLeft: 20 }}>
                  {staging.length === 0 ? (
                    <p style={{ fontSize: 11, color: C.textMuted, padding: '4px 8px' }}>No staging models yet</p>
                  ) : staging.map((m: DbtModel) => (
                    <button key={m.name} onClick={() => insertTableRef(m)}
                      style={{ display: 'flex', alignItems: 'center', gap: 6, width: '100%', padding: '6px 8px', borderRadius: 7, background: loadedModel === m.name ? 'rgba(14,165,233,0.1)' : 'none', border: 'none', cursor: 'pointer', marginBottom: 2 }}>
                      <FileCode size={12} style={{ color: C.accent, flexShrink: 0 }} />
                      <span style={{ fontSize: 12, fontFamily: 'ui-monospace, monospace', color: loadedModel === m.name ? C.accent : C.textMuted, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                        {m.name}.sql
                      </span>
                      <StatusPill status={m.status || 'success'} />
                    </button>
                  ))}
                </div>
              )}

              {/* Marts folder */}
              <button onClick={() => setMartsOpen(o => !o)}
                style={{ display: 'flex', alignItems: 'center', gap: 6, width: '100%', padding: '7px 8px', borderRadius: 7, background: 'none', border: 'none', cursor: 'pointer', color: C.textPrimary, fontSize: 13, fontWeight: 600, marginTop: 8 }}>
                {martsOpen ? <ChevronDown size={13} /> : <ChevronRight size={13} />}
                <FolderOpen size={13} style={{ color: C.violet }} />
                <span>marts/</span>
                <span style={{ marginLeft: 'auto', fontSize: 10, color: C.textMuted }}>{marts.length}</span>
              </button>
              {martsOpen && (
                <div style={{ marginLeft: 20 }}>
                  {marts.length === 0 ? (
                    <p style={{ fontSize: 11, color: C.textMuted, padding: '4px 8px' }}>No mart models yet</p>
                  ) : marts.map((m: DbtModel) => (
                    <button key={m.name} onClick={() => insertTableRef(m)}
                      style={{ display: 'flex', alignItems: 'center', gap: 6, width: '100%', padding: '6px 8px', borderRadius: 7, background: loadedModel === m.name ? 'rgba(124,58,237,0.1)' : 'none', border: 'none', cursor: 'pointer', marginBottom: 2 }}>
                      <FileCode size={12} style={{ color: C.violet, flexShrink: 0 }} />
                      <span style={{ fontSize: 12, fontFamily: 'ui-monospace, monospace', color: loadedModel === m.name ? C.violet : C.textMuted, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                        {m.name}.sql
                      </span>
                      <StatusPill status={m.status || 'success'} />
                    </button>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* Last run stats mini */}
          {lastRun && (
            <div style={{ marginTop: 'auto', padding: 16, borderTop: `1px solid ${C.border}` }}>
              <p style={{ fontSize: 11, letterSpacing: '0.08em', textTransform: 'uppercase' as const, color: C.textLabel, fontWeight: 600, margin: '0 0 10px' }}>Last dbt Run</p>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
                {[
                  { label: 'Models', value: (lastRun.models_succeeded ?? 0) + (lastRun.models_failed ?? 0), color: C.textPrimary },
                  { label: 'OK',     value: lastRun.models_succeeded ?? 0, color: C.emerald },
                  { label: 'Failed', value: lastRun.models_failed ?? 0,    color: C.red },
                  { label: 'Tests',  value: lastRun.tests_passed ?? 0,     color: C.emerald },
                ].map(s => (
                  <div key={s.label} style={{ background: C.card, border: `1px solid ${C.border}`, borderRadius: 8, padding: '8px 10px', textAlign: 'center' }}>
                    <p style={{ fontSize: 18, fontWeight: 700, color: s.color, margin: 0 }}>{s.value}</p>
                    <p style={{ fontSize: 10, color: C.textMuted, margin: 0 }}>{s.label}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Right panel — SQL Workbench 62% */}
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', background: C.bg, overflowY: 'auto' }}>
          {/* When model selected: show model details header */}
          {selectedModel ? (
            <div style={{ padding: '14px 20px', borderBottom: `1px solid ${C.border}`, background: C.card, display: 'flex', alignItems: 'center', gap: 12 }}>
              <FileCode size={16} style={{ color: selectedModel.schema_layer === 'marts' ? C.violet : C.accent }} />
              <div>
                <p style={{ fontSize: 14, fontWeight: 600, color: C.textPrimary, fontFamily: 'ui-monospace, monospace', margin: 0 }}>{selectedModel.name}.sql</p>
                <p style={{ fontSize: 11, color: C.textMuted, margin: 0 }}>{selectedModel.description || `${selectedModel.schema_layer} model`}</p>
              </div>
              <StatusPill status={selectedModel.status || 'success'} />
            </div>
          ) : (
            <div style={{ padding: '14px 20px', borderBottom: `1px solid ${C.border}`, background: C.card }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <Database size={15} style={{ color: C.accent }} />
                <p style={{ fontSize: 13, fontWeight: 600, color: C.textPrimary, margin: 0 }}>SQL Workbench</p>
                {loadedModel && (
                  <span style={{ fontSize: 11, padding: '2px 8px', borderRadius: 5, background: 'rgba(14,165,233,0.1)', color: C.accent }}>
                    inserted {loadedModel}
                  </span>
                )}
              </div>
            </div>
          )}

          <div style={{ padding: 20, display: 'flex', flexDirection: 'column', gap: 16 }}>
            {/* Editor + action buttons */}
            <div>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: 8, marginBottom: 8 }}>
                <button onClick={() => optimize.mutate()} disabled={optimize.isPending || !sql.trim()}
                  style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '7px 14px', borderRadius: 7, fontSize: 12, fontWeight: 600, cursor: 'pointer', background: 'rgba(124,58,237,0.15)', color: '#c4b5fd', border: '1px solid rgba(124,58,237,0.3)', opacity: optimize.isPending || !sql.trim() ? 0.5 : 1 }}>
                  <Zap size={12} />{optimize.isPending ? 'Optimizing…' : 'Optimize'}
                </button>
                <button onClick={() => run.mutate()} disabled={run.isPending || !sql.trim()}
                  style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '7px 14px', borderRadius: 7, fontSize: 12, fontWeight: 600, cursor: 'pointer', background: 'linear-gradient(135deg, #0EA5E9, #7C3AED)', color: 'white', border: 'none', opacity: run.isPending || !sql.trim() ? 0.5 : 1 }}>
                  <Play size={12} />{run.isPending ? 'Running…' : 'Run'}
                </button>
              </div>
              <textarea
                value={sql} onChange={e => { setSql(e.target.value); setLoadedModel(null) }}
                spellCheck={false}
                style={{ width: '100%', height: 200, padding: '12px 14px', borderRadius: 8, fontSize: 13, fontFamily: 'ui-monospace, monospace', resize: 'vertical', background: '#060D18', border: `1px solid ${C.border}`, color: '#CBD5E1', outline: 'none', boxSizing: 'border-box', lineHeight: 1.6 }}
                placeholder={PLACEHOLDER_SQL}
              />
            </div>

            {/* Optimization result */}
            {optResult && (
              <div style={{ borderRadius: 10, padding: 16, background: 'rgba(124,58,237,0.06)', border: '1px solid rgba(124,58,237,0.25)', display: 'flex', flexDirection: 'column', gap: 10 }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <span style={{ fontSize: 13, fontWeight: 600, color: C.emerald, display: 'flex', alignItems: 'center', gap: 6 }}>
                    <Zap size={13} /> {optResult.savings_percent ?? 0}% faster · ${optResult.dollar_savings?.toFixed(4) ?? '0'} saved
                  </span>
                  <div style={{ display: 'flex', gap: 8 }}>
                    <button onClick={useOptimized} style={{ fontSize: 12, padding: '4px 10px', borderRadius: 6, background: 'transparent', border: 'none', cursor: 'pointer', color: C.accent }}>Use this</button>
                    <button onClick={copyOptimized} style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: 12, padding: '4px 10px', borderRadius: 6, background: 'transparent', border: `1px solid ${C.border}`, cursor: 'pointer', color: C.textMuted }}>
                      {copied ? <><Check size={11} style={{ color: C.emerald }} /> Copied</> : <><Copy size={11} /> Copy</>}
                    </button>
                  </div>
                </div>
                {(optResult.anti_patterns?.length ?? 0) > 0 && (
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
                    {optResult.anti_patterns!.map((ap: AntiPattern) => (
                      <span key={ap.type} style={{ fontSize: 11, padding: '2px 7px', borderRadius: 5, background: 'rgba(245,158,11,0.12)', color: C.amber }}>{ap.type}</span>
                    ))}
                  </div>
                )}
                {(optResult.changes_made?.length ?? 0) > 0 && (
                  <ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>
                    {optResult.changes_made!.map((c: string, i: number) => (
                      <li key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 8, fontSize: 13, marginBottom: 4 }}>
                        <span style={{ color: C.emerald }}>•</span>
                        <span style={{ color: C.textPrimary }}>{c}</span>
                      </li>
                    ))}
                  </ul>
                )}
                {optResult.optimized_sql && <CodeBlock code={optResult.optimized_sql} language="sql" maxLines={15} />}
              </div>
            )}

            {/* Run results skeleton */}
            {run.isPending && (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                {[95, 83, 65].map((w, i) => <div key={i} style={{ height: 8, borderRadius: 4, background: C.border, width: `${w}%`, opacity: 0.8 }} />)}
              </div>
            )}

            {/* Run results table */}
            {runResult && !run.isPending && (
              <div style={{ borderRadius: 10, overflow: 'hidden', border: `1px solid ${C.border}` }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 14px', background: C.card }}>
                  <span style={{ fontSize: 12, fontWeight: 600, color: C.textPrimary, display: 'flex', alignItems: 'center', gap: 6 }}>
                    <Table2 size={13} style={{ color: C.emerald }} />
                    {runResult.row_count ?? 0} rows · {runResult.execution_time_ms ?? 0} ms
                  </span>
                  {(runResult.savings_percent ?? 0) > 0 && (
                    <span style={{ fontSize: 11, color: C.emerald }}>auto-optimized {runResult.savings_percent?.toFixed(0)}% before run</span>
                  )}
                </div>
                <div style={{ overflowX: 'auto', maxHeight: 260 }}>
                  {Array.isArray(runResult.columns) && runResult.columns.length > 0 ? (
                    <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
                      <thead>
                        <tr style={{ background: 'rgba(0,0,0,0.3)' }}>
                          {runResult.columns.map((col: string, i: number) => (
                            <th key={i} style={{ textAlign: 'left', padding: '8px 12px', fontWeight: 600, fontSize: 11, letterSpacing: '0.06em', textTransform: 'uppercase' as const, color: C.textLabel, borderBottom: `1px solid ${C.border}`, whiteSpace: 'nowrap' }}>{col}</th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {(runResult.rows || []).map((row: (string | number | null)[], ri: number) => (
                          <tr key={ri} style={{ borderBottom: `1px solid ${C.border}` }}>
                            {row.map((cell: string | number | null, ci: number) => (
                              <td key={ci} style={{ padding: '6px 12px', fontFamily: 'ui-monospace, monospace', whiteSpace: 'nowrap', color: '#CBD5E1' }}>
                                {cell === null ? <span style={{ color: '#475569', fontStyle: 'italic' }}>null</span> : String(cell)}
                              </td>
                            ))}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  ) : (
                    <p style={{ padding: '24px', textAlign: 'center', fontSize: 13, color: C.textMuted }}>Query ran successfully — no rows returned.</p>
                  )}
                </div>
              </div>
            )}

            {/* Recent runs table (when no model selected) */}
            {!selectedModel && !optResult && !runResult && !run.isPending && Array.isArray(runs) && runs.length > 0 && (
              <div style={{ background: C.card, border: `1px solid ${C.border}`, borderRadius: 10, overflow: 'hidden' }}>
                <div style={{ padding: '10px 14px', borderBottom: `1px solid ${C.border}` }}>
                  <p style={{ fontSize: 11, letterSpacing: '0.08em', textTransform: 'uppercase' as const, color: C.textLabel, fontWeight: 600, margin: 0 }}>Recent Runs</p>
                </div>
                <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
                  <thead>
                    <tr>
                      {['Run ID','Model','Status','Duration','Time'].map(h => (
                        <th key={h} style={{ textAlign: 'left', padding: '8px 14px', fontSize: 11, letterSpacing: '0.06em', textTransform: 'uppercase' as const, color: C.textLabel, fontWeight: 600, borderBottom: `1px solid ${C.border}` }}>{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {runs.slice(0, 8).map((r: DbtRunExtended, i: number) => (
                      <tr key={i} style={{ borderBottom: `1px solid ${C.border}` }}>
                        <td style={{ padding: '9px 14px', fontFamily: 'ui-monospace, monospace', color: C.textMuted, fontSize: 11 }}>{String(r.id || '').slice(0, 8)}…</td>
                        <td style={{ padding: '9px 14px', color: C.textPrimary, fontFamily: 'ui-monospace, monospace', fontSize: 12 }}>{r.model_name || '—'}</td>
                        <td style={{ padding: '9px 14px' }}><StatusPill status={r.status || 'success'} /></td>
                        <td style={{ padding: '9px 14px', color: C.textMuted }}>{r.duration_ms ? `${r.duration_ms}ms` : '—'}</td>
                        <td style={{ padding: '9px 14px', color: C.textMuted, fontSize: 11 }}>{r.created_at ? new Date(r.created_at).toLocaleString() : '—'}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {/* Hint text */}
            {!optResult && !runResult && !run.isPending && (
              <p style={{ fontSize: 12, color: C.textMuted }}>
                Write a query above, then{' '}
                <span style={{ color: '#c4b5fd' }}>Optimize</span> for AI rewrite suggestions or{' '}
                <span style={{ color: C.accent }}>Run</span> to execute it.
              </p>
            )}

            {/* Last run output detail */}
            {lastRun?.run_output && (
              <details>
                <summary style={{ cursor: 'pointer', fontSize: 12, color: C.textMuted, display: 'flex', alignItems: 'center', gap: 6 }}>
                  <ChevronRight size={13} /> View last run output
                </summary>
                <pre style={{ marginTop: 10, padding: 14, borderRadius: 8, fontSize: 11, fontFamily: 'ui-monospace, monospace', overflowX: 'auto', maxHeight: 200, background: 'rgba(0,0,0,0.4)', color: '#94a3b8', border: `1px solid ${C.border}` }}>
                  {lastRun.run_output}
                </pre>
              </details>
            )}
          </div>
        </div>
      </div>
    </motion.div>
  )
}
